secret:
  username: "cG9zdGdyZXM="
  password: "cG9zdGdyZXM="

config:
  database_url: jdbc:postgresql://192.168.0.189:5432/job4j_devops?ssl=false

containers:
  image: "ashleygt/job4j_devops:v.2.0.1"